
q_truth <- function(a, x, max_to_min){
  
  # Calculate the simulated true Q-value.
  # Input: 1. a (scalar): the continuous treatment a;
  #        2. x (scalar): the covariate x;
  #        3. max_to_min (boolean): if max_to_min=TRUE, convert the maximization problem to a minimization problem by negating the Q-value.
  # Output: y (scalar): the simulated true Q-value.
  
  y <- cos(a) + sin(x*a)
  if (max_to_min){ return(-y) # from max to min
  }else { return(y) }
}

q_function_conservative_mean <- function(a, x, phi){
  
  # Calculate the (alternative) conservative Q-value.
  # Input: 1. a (scalar): the continuous treatment a;
  #        2. x (scalar): the covariate x;
  #        3. phi (matrix, dim=c(num_samples, B*3+1)): the posterior samples of (mu_Y(dim=1), gamma(dim=B), beta_X^Y(dim=B), delta_{A*X}(dim=B)), where num_samples denotes the number of posterior samples, and B=B0-1 denotes the degrees of freedom of the cubic B-spline expansion after imposing the sum-to-zero constraint.
  # Output: y_min (scalar): the (alternative) conservative Q-value.
  
  # transfrom data to spline basis
  a_bs <- predict(a_spline, a) %*% a_trans
  x_bs <- predict(x_spline, x) %*% x_trans
  xa_bs <- predict(xa_spline, x*a) %*% xa_trans
  # calculate q-value
  y <- cbind(rep(1,length(x)),a_bs,x_bs,xa_bs) %*% t(phi)
  y_mean <- colMeans(y,dims=1); min_index <- which.min(y_mean)
  y_min <- y[,min_index] # lower bound
  # check whether out of the boundary
  out_index <- unique(c(which(a<a_lower|a>a_upper), 
                        which((x*a)<xa_lower|(x*a)>xa_upper)))
  y_min[out_index] <- 0
  return(y_min)
}

q_function_conservative <- function(a, x, phi){
    
  # Calculate the conservative Q-value.
  # Input: 1. a (scalar): the continuous treatment a;
  #        2. x (scalar): the covariate x;
  #        3. phi (matrix, dim=c(num_samples, B*3+1)): the posterior samples of (mu_Y(dim=1), gamma(dim=B), beta_X^Y(dim=B), delta_{A*X}(dim=B)), where num_samples denotes the number of posterior samples, and B=B0-1 denotes the degrees of freedom of the cubic B-spline expansion after imposing the sum-to-zero constraint.
  # Output: y_min (scalar): the conservative Q-value.
    
  # transfrom data to spline basis
  a_bs <- predict(a_spline, a) %*% a_trans
  x_bs <- predict(x_spline, x) %*% x_trans
  xa_bs <- predict(xa_spline, x*a) %*% xa_trans
  # calculate q-value
  y <- cbind(rep(1,length(x)),a_bs,x_bs,xa_bs) %*% t(phi)
  y_min <- apply(y, 1, min) # lower bound
  # check whether out of the boundary
  out_index <- unique(c(which(a<a_lower|a>a_upper), 
                      which((x*a)<xa_lower|(x*a)>xa_upper)))
  y_min[out_index] <- 0
  return(y_min)
}

q_function_expected <- function(a, x, phi, sample_phi){
    
  # Calculate the expected Q-value.
  # Input: 1. a (scalar): the continuous treatment a;
  #        2. x (scalar): the covariate x;
  #        3. phi (matrix, dim=c(num_samples, B*3+1)): the posterior samples of (mu_Y(dim=1), gamma(dim=B), beta_X^Y(dim=B), delta_{A*X}(dim=B)), where num_samples denotes the number of posterior samples, and B=B0-1 denotes the degrees of freedom of the cubic B-spline expansion after imposing the sum-to-zero constraint;
  #        4. sample_phi (boolean): if sample_phi=TRUE, calculate the Q-value using a randomly selected posterior sample (one row) from the matrix phi; otherwise, calculate the posterior expected Q-value by averaging over all posterior samples.
  # Output: y (scalar): the expected Q-value.
    
  # transfrom data to spline basis
  a_bs <- predict(a_spline, a) %*% a_trans
  x_bs <- predict(x_spline, x) %*% x_trans
  xa_bs <- predict(xa_spline, x*a) %*% xa_trans
  # calculate q-value
  if (sample_phi){ y <- as.vector(cbind(rep(1,length(x)),a_bs,x_bs,xa_bs) %*% phi[sample(1:num_samples,1),]) 
  }else{ y <- cbind(rep(1,length(x)),a_bs,x_bs,xa_bs) %*% t(phi); y <- rowMeans(y) }
  # check whether out of the boundary
  out_index <- unique(c(which(a<a_lower|a>a_upper),
                        which((x*a)<xa_lower|(x*a)>xa_upper)))
  y[out_index] <- 0
  return(y)
}

policy_function <- function(x, I, theta, std_sgd){
    
  # Evaluate the policy function at x given the policy parameter theta.
  # Input: 1. x (scalar): the covariate x;
  #        2. I (scalar): the total number of individuals;
  #        3. theta (vector, dim=(B)): the parameter vector for the policy function based on a cubic B-spline basis expansion;
  #        4. std_sgd (scalar): the standard deviation parameter of the policy function used in the SGD algorithm, corresponding to the notation sigma_pi in the manuscript.
  # Output: a (scalar): the treatment/action generated by the policy function.
    
  # transfrom data to spline basis
  x_bs <- predict(x_spline, x) %*% x_trans
  x_pred <- cbind(rep(1,length(x)), x_bs)
  # generate treatment/action
  a <- x_pred %*% theta + rnorm(I,0,std_sgd)
}

grad_expected_reward <- function(a, x, theta, y, std_sgd){
    
  # Calculate the gradient of the expected reward using the policy gradient formula.
  # Input: 1. a (scalar): the continuous treatment a;
  #        2. x (scalar): the covariate x;
  #        3. theta (vector, dim=(B)): the parameter vector for the policy function based on a cubic B-spline basis expansion;
  #        4. y (scalar): the outcome y;
  #        5. std_sgd (scalar): the standard deviation parameter of the policy function used in the SGD algorithm, corresponding to the notation sigma_pi in the manuscript.
  # Output: grad (scalar): the gradient of the expected reward used in the SGD algorithm.
    
  # transfrom data to spline basis
  x_bs <- predict(x_spline, x) %*% x_trans
  x_pred <- cbind(rep(1,length(x)), x_bs)
  # calculate gradient of log policy
  grad_log_policy <- as.vector((a - x_pred %*% theta)/std_sgd^2) * x_pred
  # calculate the gradient of expected reward
  grad <- colSums(as.vector(y) * grad_log_policy)
  return(grad)
}
